---
title: "252E Final Project Part 1 \n Relationship between Frequency of Care and Progression to Hepatocellular Carcinoma \n among Chronic Hepatitis C Patients"
author: "Stephanie Holm and Shelley Facente"
date: "10/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(skimr)

knitr::opts_chunk$set(include = FALSE, cache = TRUE)

HCVData <- read_excel("Deidentified Chronic HCV Dataset 9-10-19 (1).xlsx")

```

```{r Data Cleaning}
#Let's do all Variable prep/Data cleaning in this chunk

#first just making variables their proper type
HCVData$`Deidentified Pt Numb`<- as.factor(HCVData$`Deidentified Pt Numb`)
colnames(HCVData)[colnames(HCVData) == 'Deidentified Pt Numb'] <- 'PtID'

HCVData$`Hep Visit`<- as.factor(HCVData$`Hep Visit`)
colnames(HCVData)[colnames(HCVData) == 'Hep Visit'] <- 'EverHepVisit'

HCVData$`Ever Chronic HCV` <- as.factor(HCVData$`Ever Chronic HCV`)
HCVData$`Spontaneous Clearance?` <- as.factor(HCVData$`Spontaneous Clearance?`)
HCVData$`Ever Ab positive HCV` <- as.factor(HCVData$`Ever Ab positive HCV`)
HCVData$`Ever Treated`<- as.factor(HCVData$`Ever Treated`)
HCVData$`SVR Achieved`<- as.factor(HCVData$`SVR Achieved`)
HCVData$`Treatment Definition` <- as.factor(HCVData$`Treatment Definition`)

HCVData$`DX_TYPE OR TEST_TYPE-Reason for inclusion` <- as.factor(HCVData$`DX_TYPE OR TEST_TYPE-Reason for inclusion`)
colnames(HCVData)[colnames(HCVData) == 'DX_TYPE OR TEST_TYPE-Reason for inclusion'] <- 'inclusion.source'

HCVData$`DX_NAME OR TEST RESULT-Reason for inclusion`<- as.factor(HCVData$`DX_NAME OR TEST RESULT-Reason for inclusion`)
colnames(HCVData)[colnames(HCVData) == 'DX_NAME OR TEST RESULT-Reason for inclusion'] <- 'inclusion.reason'

colnames(HCVData)[colnames(HCVData) == 'SPECIMN TAKEN DATE of first positive'] <- 'date.first.pos.HCV.test'

HCVData$RESULT <- as.factor(HCVData$RESULT)
colnames(HCVData)[colnames(HCVData) == 'RESULT'] <- 'HCV.test.result'

```
## Description of our Dataset

## Proposed Causal Question
-Inclusion criteria
-Outcome
-Intervention Nodes
-Counterfactual outcomes of interest
-Target Causal parameter

##Identification and Estimand

##Preliminary Feasibility assessment

